### PR TITLE
MergeColumns and TimeFormat options for importing csv

### PR DESCRIPTION
**Pull request by zdevwu**
Added the ability to merge columns and customise the time format when parsing time values

### CODE REVIEW

**Comment by pjebs** [comment]
Can you explain what it does and provide an example

**Comment by zdevwu** [comment]
@pjebs the code comment and tests should explain

**Comment by zdevwu** [comment]
these two features combine to achieve the `parse_dates` options in pandas `read_csv`
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html

**Comment by pjebs** [comment]
Thank you for your contribution.

The ability to parse custom date formats are already implemented. Your current implementation only allows 1 custom format when different columns may have different date formats.

Currently it is possible using: https://godoc.org/github.com/rocketlaunchr/dataframe-go/imports#Converter

With regards to the "merging", it can done using Apply using InPlace: true: https://godoc.org/github.com/rocketlaunchr/dataframe-go#Apply and then deleting one of the series.

**Pull request closed without merging**
