### PR TITLE
add Input/Output to csv and json

### PR DESCRIPTION
**Pull request by kzoper**
function works. 
But tests fails, i don't know why 

```golang 
        f,_ := os.Create("test.csv")
	defer f.Close()
	s1 := dataframe.NewSeriesInt64("day", nil, 1,2,3)
	s2 := dataframe.NewSeriesString("sales", nil, "a","b","q,w")
	df := dataframe.NewDataFrame(s1, s2)
	df.ToCSV(f,dataframe.CSVOptions{
		Comma:            ',',
		Comment:          0,
		TrimLeadingSpace: false,
		LazyQuotes:       false,
	})

        f,_ = os.Open("test.csv")
        defer f.Close()
	df1,_ := dataframe.FromCSV(f)
	fmt.Println(df1)
```

```golang
        f,_ := os.Create("test.json")
        defer f.Close()
	s1 := dataframe.NewSeriesInt64("day", nil, 1,2,3)
	s2 := dataframe.NewSeriesString("sales", nil, "a","b","q,w")
	df := dataframe.NewDataFrame(s1, s2)
	df.ToJSON(f)
	f.Close()

	f, _ = os.Open("test.json")
	defer f.Close()
	df1, _ := dataframe.FromJSON(f)
	fmt.Println(df1)
```

JSON import works only with `[][]string` file structure

### CODE REVIEW

**Comment by rocketlaunchr-cto** [comment]
Great work @kzoper 
I will look at this next weekend. However, my current thinking is changing the `import` package into `io` and having your functions inside that package rather than trying to replicate the pandas library function for function.

The reason why I am leaning that way is that the core functionality should be kept separate from enhancement functionality. Some users won't be using these import/export features so by including them in the main package will just increase the binary. Go files are already quite large.

**Comment by rocketlaunchr-cto** [comment]
What's the exact error you get when tests fail?

**Comment by tappoz** [comment]
Is there any news on this CSV/JSON in/out?
I just found out the unexpected `panic` on the empty function body here: https://github.com/rocketlaunchr/dataframe-go/blob/master/imports/imports.go#L76 
That's useless so I am wondering if there is any plan to merge/harmonize the code in here?
Thanks

**Comment by pjebs** [comment]
I guess it card be too hard to implement a json import.
I'll give it a try within a month.

It will have to use the json Decoder instead of unmarshaler however.

**Comment by rocketlaunchr-cto** [comment]
@tappoz json importing has been implemented. Check the `json-imports` branch to give me feedback before I merge it to master.

**Comment by rocketlaunchr-cto** [comment]
importing and exporting functionality has now been added.

**Pull request closed without merging**
